### ISSUE TITLE
多个选择框 怎么拿到最后选中的数值

### ISSUE THREAD

**Issue by MWLBear** [Hanwp/HWDownSelectedView#1]
@Hanwp

**Comment by CCat00** [comment]
这个没有什么影响吧，直接拿就可以了。

**Comment by MWLBear** [comment]
我界面上三个 选择框,走的是同一个delegate 怎么确定每个选择框的值啊

**Comment by CCat00** [comment]
- (void)downSelectedView:(HWDownSelectedView *)selectedView didSelectedAtIndex:(NSIndexPath *)indexPath;
这个代理不是回调的有selectedView吗，你可以根据这个判断

**Comment by MWLBear** [comment]
好的 谢谢了
